### ISSUE TITLE
ValueError: unknown locale: UTF-8

### ISSUE THREAD

**Issue by x-ji** [bonndan/ansible-userguide-pdf#5]
When I was trying to run `python build-site.py ../ansible/docsite/rst/`, I got the following error:

```
Traceback (most recent call last):
  File "build-site.py", line 25, in <module>
    from sphinx.application import Sphinx
  File "/usr/local/lib/python2.7/site-packages/sphinx/application.py", line 26, in <module>
    from docutils.parsers.rst import convert_directive_function, \
  File "/usr/local/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 74, in <module>
    import docutils.statemachine
  File "/usr/local/lib/python2.7/site-packages/docutils/statemachine.py", line 113, in <module>
    from docutils import utils
  File "/usr/local/lib/python2.7/site-packages/docutils/utils/__init__.py", line 20, in <module>
    import docutils.io
  File "/usr/local/lib/python2.7/site-packages/docutils/io.py", line 18, in <module>
    from docutils.utils.error_reporting import locale_encoding, ErrorString, ErrorOutput
  File "/usr/local/lib/python2.7/site-packages/docutils/utils/error_reporting.py", line 47, in <module>
    locale_encoding = locale.getlocale()[1] or locale.getdefaultlocale()[1]
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

**Comment by bonndan** [comment]
lmgtfy .... http://stackoverflow.com/questions/1830394/python-locale-strange-error-whats-going-on-here-exactly

This is most probably not an error related to this project.
